[phases.setup]
nixPkgs = ['...', 'php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.dom', 'php82Extensions.curl', 'php82Extensions.gd', 'php82Extensions.zip']

[phases.build]
cmds = [
    'npm install',
    'npm run build',
    'composer install --optimize-autoloader --no-dev'
]

[phases.deploy]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
